lib/chainer.rb
lib/chainer/configuration.rb
lib/chainer/function.rb
lib/chainer/functions/math/basic_math.rb
lib/chainer/utils/argument.rb
lib/chainer/utils/array.rb
lib/chainer/utils/variable.rb
lib/chainer/variable.rb
lib/chainer/variable_node.rb
red-chainer.gemspec

Add Variable, Function And Base Operator

---

LICENSE.txt

Add Copyright holder, reference https://github.com/chainer/chainer/blob/master/LICENSE.

Add Copyright holder

---

examples/mnist.rb

Add MLP sample
usage:
```sh
$ bundle install
$ bundle exec ruby examples/mnist.rb
```

Add MLP example

---

lib/chainer/functions/loss/softmax_cross_entropy.rb
lib/chainer/hyperparameter.rb
lib/chainer/initializers/constant.rb
lib/chainer/initializers/init.rb
lib/chainer/iterators/serial_iterator.rb
lib/chainer/links/connection/linear.rb
lib/chainer/links/model/classifier.rb
lib/chainer/optimizer.rb
lib/chainer/optimizers/adam.rb
lib/chainer/parameter.rb
lib/chainer/variable.rb

- Add UpdateRule, AdamRule
- Correction of Numo::NArray part

Change accuracy calculation logic

---

README.md
examples/mnist.rb

Add Installation and Usage to README.md

---

lib/chainer/iterators/serial_iterator.rb

Fixed a bug that epoch does'nt work well.

FIX @current_position indent

---

lib/chainer/dataset/download.rb
lib/chainer/datasets/mnist.rb

- fix https://github.com/red-data-tools/red-chainer/issues/10
- fix load mnist datasets

FIX cache_or_load_file method and load mnist datasets

---

lib/chainer/iterators/serial_iterator.rb
lib/chainer/link.rb
lib/chainer/links/model/classifier.rb
lib/chainer/reporter.rb
lib/chainer/training/extensions/log_report.rb
lib/chainer/training/extensions/print_report.rb
lib/chainer/training/extensions/progress_bar.rb
lib/chainer/training/standard_updater.rb
lib/chainer/training/trainer.rb
lib/chainer/training/triggers/interval.rb
lib/chainer/training/updater.rb

- add LogReport, PrintReport, ProgressBar extenions

Add LogReport, PrintReport, ProgressBar extensions

---

lib/chainer/variable.rb
test/variable_test.rb

Add VariableTest and add ndim method for Variable class.

Add VariableTest

---

.travis.yml

- add ruby 2.4.2, 2.3.5 to .travis.yml
- add `ruby test/run_test.rb`

Add ruby2.4.2, 2.3.5 ​​and test-unit to travis config file

---

.travis.yml

TravisCI support 2.5.0

---

lib/chainer/optimizer.rb
test/optimizer_test.rb

WeightDecay

---

lib/chainer/functions/pooling/max_pooling_2d.rb
test/functions/pooling/max_pooling_2d_test.rb

MaxPooling2D Backward

---

lib/chainer/functions/connection/convolution_2d.rb
test/functions/connection/convolution_2d_test.rb

Convolution2DFunction backward

---

lib/chainer/datasets/cifar.rb
lib/chainer/links/normalization/batch_normalization.rb

Red Chainer is use [SFloat](https://github.com/red-data-tools/red-chainer/pull/48)
So DFloat will change to SFloat

Change DFloat to SFloat

---

examples/cifar/models/resnet18.rb
examples/cifar/models/vgg.rb
examples/cifar/train_cifar.rb
lib/chainer/datasets/tuple_dataset.rb
lib/chainer/initializers/init.rb
lib/chainer/link.rb

ref. https://arxiv.org/pdf/1512.03385.pdf

Add ResNet-18

---

README.md

* Implementation status added
* Name and Description field updated.

Implementation status added

---

lib/chainer/iterators/serial_iterator.rb
lib/chainer/reporter.rb
lib/chainer/training/extensions/evaluator.rb

porting [Evaluator extension](https://github.com/chainer/chainer/blob/v2.1.0/chainer/training/extensions/evaluator.py#L14)

Support Evaluator Extension

---

lib/chainer/datasets/cifar.rb

It's available since red-datasets 0.0.5.
NOTE: red-datasets 0.0.5 isn't released yet.
I just want to ask how do you think about this API.

cifar: use Datasets::Table#[] API

---

README.md

fix example path.

---

lib/chainer/training/extension.rb
lib/chainer/training/extensions/evaluator.rb
lib/chainer/training/extensions/exponential_shift.rb
lib/chainer/training/extensions/log_report.rb
lib/chainer/training/extensions/print_report.rb
lib/chainer/training/extensions/progress_bar.rb
lib/chainer/training/extensions/snapshot.rb

- fix extension's priority, trigger, name definition
- delete with no need space

fix extension's priority, trigger, name definition

---

README.md
examples/mnist/mnist.rb
lib/chainer/datasets/mnist.rb

http://yann.lecun.com/exdb/mnist/ uses "MNIST" not "Mnist".

Rename MNIST from Mnist

---

lib/chainer/functions/loss/softmax_cross_entropy.rb
test/functions/loss/softmax_cross_entropy_test.rb

Sorry, I made a bug via https://github.com/red-data-tools/red-chainer/pull/67.

Fix softmax_cross_entropy

---

red-chainer.gemspec
test/dataset/convert_test.rb
test/functions/activation/leaky_relu_test.rb
test/functions/activation/log_softmax_test.rb
test/functions/activation/relu_test.rb
test/functions/activation/sigmoid_test.rb
test/functions/activation/tanh_test.rb
test/functions/array/broadcast_to_test.rb
test/functions/array/reshape_test.rb
test/functions/loss/mean_squared_error_test.rb
test/functions/loss/softmax_cross_entropy_test.rb
test/gradient_check_test.rb
test/initializers/uniform_test.rb
test/utils/array_test.rb
test/variable_test.rb

Updated test code using test data matrix generation of test-unit 3.2.9.
Please refer to the following for improvement contents of test-unit 3.2.9.
* https://github.com/test-unit/test-unit/blob/master/doc/text/news.md

Updated test code using test data matrix generation of test-unit 3.2.9.

---

lib/chainer/functions/array/select_item.rb
lib/chainer/functions/connection/convolution_2d.rb
lib/chainer/functions/connection/deconvolution_2d.rb
lib/chainer/functions/loss/softmax_cross_entropy.rb
lib/chainer/functions/pooling/max_pooling_2d.rb
lib/chainer/gradient_check.rb
test/function_node_test.rb
test/functions/activation/tanh_test.rb
test/functions/array/rollaxis_test.rb
test/functions/array/select_item_test.rb
test/functions/connection/convolution_2d_test.rb
test/functions/connection/deconvolution_2d_test.rb
test/functions/loss/softmax_cross_entropy_test.rb
test/functions/math/sum_test.rb
test/functions/noise/dropout_test.rb
test/functions/normalization/batch_normalization_test.rb
test/functions/pooling/average_pooling_2d_test.rb
test/functions/pooling/max_pooling_2d_test.rb
test/links/connection/embed_id_test.rb
test/utils/array_test.rb
test/variable_test.rb

follow-up: https://github.com/red-data-tools/red-chainer/pull/84
everything is not passed yet, though
TODO
* select_items
* deconvolution_2d
* max_pooling_2d

support cumo

---

lib/chainer/functions/connection/convolution_2d.rb

see https://github.com/chainer/chainer/blob/e622e7acb4767fdb3bdd66060f58555252337f4d/chainer/functions/connection/convolution_2d.py#L232-L234

fix conv2d

---

examples/cifar/train_cifar.rb
lib/chainer/cuda.rb
lib/chainer/functions/connection/convolution_2d.rb
lib/chainer/functions/connection/convolution_2d_grad_w.rb
lib/chainer/functions/connection/deconvolution_2d.rb
lib/chainer/functions/normalization/batch_normalization.rb
lib/chainer/functions/pooling/average_pooling_2d.rb
lib/chainer/functions/pooling/pooling_2d.rb

which is supported by cumo >= 0.3.0.
* Chainer::CUDA.cudnn_enabled?
* env RED_CHAINER_CUDNN=1|0

Support cuDNN

---

lib/chainer/gradient_check.rb

Numo::NArray (Cumo::NArray) + rational is not supported.

Fix gradient_check for cumo

---

lib/chainer/functions/normalization/batch_normalization.rb

fixed_batch_norm: use cudnn
